#!/bin/sh
set -e -u

# This tool creates a root filesystem image for the Beagleboard XM.

die () {
	echo "$@" >&2
	exit 1
}

USAGE="${0##./}"' [-C] [-c config] [package]
  Options:
    -C          print default config template to stdout and exit
    -c config   use file <config> as alternate config template

  Environment:
    The command line takes precedence over the environment.
    MKOS_CONFIG  - multistrap configuration
    MKOS_PACKAGE - root package
'

DEFAULT_CONFIG=/usr/share/mkos-beaglexm/default.mstrap
DEFAULT_PACKAGE=device-beaglexm

while [ "$#" != 0 ]
do
	case "$1,${2-}" in
		-C,*)
			cat $DEFAULT_CONFIG
			exit
			;;
		-c,?*)
			TEMPLATE="$2"
			shift
			shift
			;;
		-*)
			die "$USAGE"
			;;
		*)
			test -n "${PACKAGE:-}" && die "$USAGE"
			PACKAGE="$1"
			shift
			;;
	esac
done

: ${TEMPLATE:=${MKOS_CONFIG-$DEFAULT_CONFIG}}
: ${PACKAGE:=${MKOS_PACKAGE-$DEFAULT_PACKAGE}}
test $(whoami) = "root" || die "error: must be root or preferably fakeroot"
test -r "$TEMPLATE" || die "error: file $TEMPLATE is unreadable"
IMAGE=ptux.img
test ! -e "$IMAGE" || die "error: refusing to overwrite $IMAGE"
TARBALL=ptux.tgz
test ! -e "$TARBALL" || die "error: refusing to overwrite $TARBALL"
BUILD=ptux.rootfs
IMAGESIZE=$(expr 512 \* 1024 \* 1024)
CONFIG=$(mktemp --tmpdir mkos-beaglexm-XXXXXXXXXX.mstrap)

trap "rm -rf $CONFIG $BUILD $IMAGE $TARBALL; exit" INT TERM EXIT

sed -e "s/{{.*package.*}}/$PACKAGE/" $TEMPLATE >$CONFIG
/usr/sbin/multistrap -f $CONFIG -d $BUILD
rm $CONFIG

# TODO: real work, i.e.:
#
#   sudo dd if=/dev/zero of=${DISK} bs=1M count=16
#   sudo sfdisk --in-order --Linux --unit M ${DISK} <<-__EOF__
#   1,48,0xE,*
#   ,,,-
#   __EOF__
#
# The contents of BUILD/boot go into the vfat partition, and
# the rest goes into the ext4 partition.
#

tar czf $TARBALL $BUILD
rm -r $BUILD
trap - INT TERM EXIT
